christmas maptest configs
gflze/CS2-ZE-Configs pull request #7
Opened 2024-04-13 18:39 UTC by TheBigBadMemeMan

map test hotfixes

2024-04-13 19:18 UTC, Vauff requested changes
This won't work, you have two root blocks instead of one which is invalid JSON. Also `add` is an array of blocks, you can just copy the 2nd add block into the first array.

2024-04-13 19:28 UTC, TheBigBadMemeMan commented
do comments work the same way? but i updated the formatting and check on some json checker website lmao

2024-04-13 19:37 UTC, TheBigBadMemeMan commented
add angles

2024-04-19 01:15 UTC, Vauff approved these changes

2024-04-19 01:15 UTC, merged